### ISSUE TITLE
Неверная интерпретация кода 

### ISSUE THREAD

**Issue by andrey-ilyin** [Desire4sorrow/backend#1]
https://github.com/Desire4sorrow/backend/blob/9eaecc898622a6c05fa9a3e9736b12f958a3009a/1%20lab#L33

**Comment by Desire4sorrow** [comment]
Ресурс "временно отсутствует", в таких ситуациях используется перенаправление.

**Comment by andrey-ilyin** [comment]
Опишите подробнее механику перенаправления.
