### ISSUE TITLE
Описание стуации неточное

### ISSUE THREAD

**Issue by andrey-ilyin** [Desire4sorrow/backend#2]
https://github.com/Desire4sorrow/backend/blob/9eaecc898622a6c05fa9a3e9736b12f958a3009a/1%20lab#L37

**Comment by Desire4sorrow** [comment]
400 BR - Bad Request. (аналогично, неудачный запрос от пользователя). 
Это ошибка. Для ее исправления в URL: http://localhost/lw1/javascript_is_a_client_side_language.php?how_to_work=hardly необходимо заменить "hardly" на "hard", то есть присвоить значение "hard" ключу "how_to_work" .
Итоговая ссылка: http://localhost/lw1/javascript_is_a_client_side_language.php?how_to_work=hard

**Comment by andrey-ilyin** [comment]
Принято.
