### ISSUE TITLE
Используйте return

### ISSUE THREAD

**Issue by andrey-ilyin** [Desire4sorrow/backend#3]
https://github.com/Desire4sorrow/backend/blob/bc894c83ab22a1ba0aa2e738d5238cbcc8805403/3.%20Remove_Duplicates/remove_duplicates/Program.cs#L16

Использование Exit излишне, лучше обойтись return.

**Comment by Desire4sorrow** [comment]
заменил 'Environment.Exit(1)' на 'return 1'.
Понял замечание, оно связано с категоричностью Exit, а конкретнее - немедленное завершение работы приложения, даже если работают другие потоки.

**Comment by andrey-ilyin** [comment]
Принято.
